### ISSUE TITLE
Long api keys are possibly getting truncated

### ISSUE THREAD

**Issue by keiserjb** [backdrop-contrib/key#3]
I required the Key module with the [OpenAI](https://github.com/backdrop-contrib/openai) module.

Newer API keys from OpenAI are quite long.  I've gotten issues about it.
[https://github.com/backdrop-contrib/openai](https://github.com/backdrop-contrib/openai)

[https://github.com/backdrop-contrib/openai/issues/25](https://github.com/backdrop-contrib/openai/issues/25)

The reason I'm here is that I went over to OpenAI and generated a new key.  I gave me the new format.

Legacy keys start with sk-
New keys start with sk-proj-

The new keys are quite a bit longer than the old ones.  I went to the key module and used the configuration provider.  I pasted the new API key into the field.  The field truncated the key.  I then went into text_field.inc in the key module code.  I changed the field to accept a maxlength of 256.

`$form['key_value'] = array(
    '#type' => 'textfield',
    '#title' => t('Key value'),
    '#required' => $key_provider['key value']['required'],
    '#default_value' => $key_value_data['current'],
    // Tell the browser not to autocomplete this field.
    '#attributes' => array(
      'autocomplete' => 'off',
      'maxlength' => 256, // Adjust this value as needed.
    ),
  );`
  
  Then I repasted the API key into the field.  It was no longer truncated, however when I saved it I got,
  
  Key value cannot be longer than 128 characters but is currently 164 characters long.
  
  It appears the Key module is limiting the length of the API keys somewhere.

**Comment by herbdool** [comment]
@keiserjb can you test it by changing it to use textarea instead of text?

**Comment by keiserjb** [comment]
That's one of the things I was going to try.  Changing it to a textarea did actually save the key and the module works.  

There is however, already a plugin for textarea_field.inc in the module.

**Comment by stpaultim** [comment]
@herbdool - I was the first one to run into this problem, testing the OpenAI module. So, I tried it too.

WHOOPS, seconds too late. I was about to confirm that changing the field to text area seems to solve it. But, as usual, @keiserjb was a few steps ahead of me.

**Comment by herbdool** [comment]
Not sure what you mean @keiserjb. There's also a plug-in for textarea. https://github.com/backdrop-contrib/key/blob/1.x-3.x/plugins/key_input/textarea_field.inc

**Comment by stpaultim** [comment]
Not sure if this is hepful, but changing this in "text_field.inc" from `textfield` to `textarea` seems to help.

![image](https://github.com/user-attachments/assets/8a0af6b1-562a-43e5-ad1c-7ebd6ed29e25)

**Comment by keiserjb** [comment]
I'm thinking there is a reason why there is a file for a text field text_field.inc and a text area textarea_field.inc.  They probably shouldn't both provide textareas.

**Comment by herbdool** [comment]
@keiserjb I've got a PR for using `textarea_field` with authentication if stored in config. I don't see any reason why it can't always do so. Encryption will still use `text_field` since the key size is unlikely to exceed a regular textfield. The PR also updates existing keys in config since Key stores all of the key configuration along with the key value.

**Comment by keiserjb** [comment]
That does appear to do the trick.  Thanks.
